.gitignore, README.adoc, package.json
- I've just put npm tasks in scripts section for convenience.
`npm run build`
`npm run build:watch`
`npm run start`
- Idea project folder added to .gitignore
=> package.json: scripts sections added

README.adoc, package.json, src/components/accounts/list.js
- I've changed port to 8000 because Parity use 8080 for wallet UI.
- Parity hint about CORS added to README
=> Local port changed to 8000 and README updated wit Parity hint

.travis.yml, electron/main.js, package.json, src/store/contractActions.js, src/store/contractReducers.js, src/store/contractReducers_test.js, src/tests.js
`npm run start:electron` will run app in Electron.
- fix bug with undefined contracts collection in reducer and test added
- added initial support for Electron environment `npm run start:electron`
=> Lake of Electron environment support

.babelrc, .gitignore, README.adoc, electron/main.js, electron/menus/win-linux.js, electron/package.js, electron/webpack.electron.js, package.json
`npm run package` command added. This command will build package with emerald for current platform and arch in release folder.
=> Electron packaging

src/lib/convert.js, src/lib/convert_test.js
=> lib/convert.js: check for hex string mod 2

src/components/accounts/add/importjson.js, src/components/addressbook/form.js, src/components/contracts/add.js, src/components/tx/create.js, src/components/tx/createTxForm.js, src/lib/rpcApi.js, src/store/accountActions.js, src/store/accountReducers.js, src/store/addressActions.js, src/store/contractActions.js, src/store/networkActions.js, src/store/tokenActions.js
- tx/create.js file refactored into CreateTxForm (presentation) and CreateTx (container)
- RpcApi.call() returns Promise which reject in case json rpc response contains 'error' field.
=> create tx component refactored, new RpcApi.call2() method

src/components/tx/create.js, src/components/tx/createTxForm.js
One function got lost in the merge & refactor. Please note that Send Tx still does not work.
=> components/tx/create, createTxForm: function missing from merge/refactor

src/components/tx/create.js, src/store/tokenActions.js
#67 eth_traceCall invalid params, remove password
=> components/tx/create, store/tokenActions: remove password from traceCall

package.json
Issue #88 can't resolve    "i18next-xhr-backend"
=> package.json:   add i18next-xhr-backend

src/components/accounts/add/add.js, src/components/accounts/add/generate.js, src/components/accounts/add/importjson.js, src/components/accounts/list.js, src/components/accounts/show.js, src/components/main.js, src/locales/en/accounts.json, src/locales/en/common.json, src/locales/zh-cn/accounts.json, src/locales/zh-cn/common.json
Implements `en` and `zh-cn` translation for the account components, main menu and other common ones.
=> Chinese Translation for Accounts Page

src/components/accounts/account.js
=> components/account/account.js: dont sub address for missing name

src/components/tx/create.js, src/components/tx/createTxForm.js
#102 
I could not reproduce the invalid RPC error, but this should fix the missing balance
=> components/tx/create, createTxForm: init balance val

src/components/accounts/show.js, src/components/contracts/deploy.js, src/components/contracts/interactForm.js, src/components/tx/create.js, src/components/tx/createTxForm.js, src/lib/types.js, src/store/accountActions.js, src/store/accountReducers.js, src/store/store.js
=> Load pending transactions on account load

package.json, src/components/accounts/show.js, src/components/layout/header.js, src/components/layout/status.js, src/components/layout/total.js, src/lib/types.js, src/store/accountActions.js, src/store/accountReducers.js, src/store/store.js
Currently hardcoded as USD, but opens the door to localizing currency rates and displays. 
I think there is an issue with `toLocaleString()` not working as expected... maybe because of webpacking?
- 0e02b9b Formats header to look more like latest mockup design
=> display totals & exchange rate in usd

.gitignore, electron/downloader.js, electron/launcher.js, electron/main.js, electron/mainWindow.js, electron/package.js, electron/verify.js, electron/webpack.electron.js, package.json, src/lib/rpcApi.js, src/store/tokenActions.js
Electron App will download, verify PGP signature, upzip and run Geth. Then use it directly, not through Connector
=> Download and run Geth

src/lib/rpcApi.js
solution: reject promise and log error verbosely
does not attempt to address/find the root of the issue at this time
rel #147
=> rpcapi: problem: emerald method receives undefined call

src/components/layout/footer.js, src/components/main.js, src/components/main.scss
=> cmpnts: footer component with beta release content

src/store/accountActions.js, src/store/accountReducers.js
Issue #182: accounts#generate
also Issue #181: corrupted input parameters
=> store/accountReducers: generate does not display name/descr

.travis.yml, electron/launcher.js, electron/services.js, package.json
also fix: `npm run build:all` command
=> fix: problem: dev env doesn't wait for getting emerald 

README.adoc
solution: rough draft of a more comprehensive and up-to-date guide
=> problem: README develop/build instructions are outdated

electron/nodecheck.js, electron/services.js
solution: try to connect before launch
rel: #221 #236
=> problem: can't reuse existing Geth

electron/nodecheck.js, src/components/accounts/balance.js, src/components/layout/total.js, src/store/launcherActions.js, src/store/launcherReducers.js
#195 (USD conversion)
#189 (reload accounts list)
#241 (cannot launch with local testnet)
#242 (cannot switch to mainnet)
=> Fix problems related to morden testnet (189, 195, 241, 242)

src/components/accounts/export.js, src/components/accounts/show.js, src/elements/dl.js, src/lib/rpcApi.js, src/store/accountActions.js
On the account view `EXPORT` button added. This allows users to backup their keys from emerald connector.
=> Export account as a json file

src/components/layout/total.js, src/components/tx/create.js, src/components/tx/createTxForm.js, src/store/accountReducers.js
=> TX Form Design

appveyor.yml
link: https://appveyor.tenderapp.com/discussions/problems/7115-curl-cant-download-files-through-ssl
=> problem: rust can't be installed on appveyor

src/components/layout/header.js
solution: disable ripple effect
rel: #294
=> problem: setting button becomes black circle

src/components/tx/CreateTx/create.js
If account balance is zero _entire balance_ button sets tx value to zero
=> Fixed. Tx creation: incorrect entire balance calculation

src/i18n/locales/ko-KR/accounts.json
=> Update Korean Translation

package.json, src/components/accounts/AccountShow/show.js, src/components/accounts/ExportPaperWallet/exportPaperWallet.js, src/components/accounts/GenerateAccount/PasswordDialog/passwordDialog.js, src/components/accounts/add/ImportJson/importJson.js, src/components/accounts/add/ImportPrivateKey/importPrivateKey.js, src/components/common/DashboardButton/dashboardButton.js, src/components/common/DashboardButton/dashboardButton.scss, src/components/common/DashboardButton/dashboardButton.test.js, src/components/common/DashboardButton/index.js, src/components/layout/Dashboard/menu.js, src/components/settings/settings.js, src/components/tx/CreateTx/createTxForm.js, src/components/tx/TxDetails/show.js, src/components/tx/TxHistory/List/list.js, src/components/tx/TxHistory/List/transaction.js, src/components/tx/TxHistory/history.js, src/containers/PaperWallet/paperWallet.js, src/containers/Screen/screen.js, src/elements/Form/form.js, src/elements/Icons/arrowLeftIcon.js, src/elements/Icons/index.js
Solution: new DashboardButton refactored from Form component. Form component has backButton prop now where you can provide own button
=> Problem: on some forms we do not need back/dashboard button

src/lib/traceCall.js
=> fix(send transaction):

package.json
=> Run Jest within Electron

package.json
heres the fix in `electron-builder`: https://github.com/develar/electron-builder/commit/d56326b6bd9b5f76457a63923150029b6b58cc37
fixes #352
=> feature(upgrade electon builder to fix hidden file dmg):

src/components/accounts/GenerateAccount/DownloadDialog/downloadDialog.js, src/components/accounts/GenerateAccount/PasswordDialog/passwordDialog.js, src/components/accounts/GenerateAccount/ShowPrivateDialog/showPrivateKeyDialog.js, src/components/accounts/GenerateAccount/generateAccount.js, src/components/accounts/HideAccountDialog/hideAccountDialog.js, src/components/accounts/ReceiveDialog/receiveDialog.js, src/components/accounts/add/ImportJson/fileDropField.js, src/components/accounts/add/ImportJson/importJson.js, src/components/accounts/add/ImportPrivateKey/importPrivateKey.js, src/components/dialog.js, src/components/landing/landing.js, src/components/landing/landing.scss, src/components/layout/Main/main.js, src/components/ledger/ImportAccount/buttons.js, src/components/ledger/ImportAccount/importAccount.js, src/components/ledger/WaitDialog/waitDialog.js, src/containers/Screen/screen.js, src/i18n/locales/en-US/accounts.json, src/index.js, src/store/store.js
=> feature(landing page when no wallets exist):

electron/ipc/getPrivateKey.js, electron/ipc/index.js, src/components/accounts/GenerateAccount/DownloadDialog/downloadDialog.js, src/components/accounts/GenerateAccount/PasswordDialog/passwordDialog.js, src/components/accounts/GenerateAccount/generateAccount.js, src/components/accounts/GenerateAccount/getLoadingIcon.js
=> feature(account generation loading/progress icons):

src/components/accounts/ReceiveDialog/DepositOptions/depositOptions.js, src/components/accounts/ReceiveDialog/receiveDialog.js, src/components/dialog.js
=> feature(shapeshift):

src/components/tx/TxHistory/Header/filter.js, src/components/tx/TxHistory/Header/header.js, src/components/tx/TxHistory/history.js, src/store/wallet/history/historyActions.js, src/store/wallet/history/selectors.js, src/store/wallet/history/selectors.test.js
ALSO:
problem: tx search does not work
fixes #390
fixes #396
=> problem: tx filter does not work

package.json
=> Fixed #408: Wrong version in package.json

src/components/layout/NotificationBar/NotificationBar.js, src/components/tx/TxHistory/List/transaction.js, src/components/tx/TxHistory/history.js, src/store/wallet/index.js, src/store/wallet/screen/screenReducers.js, src/store/wallet/screen/screenReducers.test.js, src/store/wallet/settings/settingsActions.js, src/store/wallet/walletActions.js
Solution: Detect that address is not in our vault and show notification with error
This PR changes NotificationBar logic.
Fixes #404
=> Problem: when user click on external address on tx history list it causes error

src/components/landing/landing.js, src/components/layout/Header/header.js, src/components/welcome/welcome.js
=> solution: update to new emerald logo

scripts/download-emerald.js
Fixes #417 - hardware wallet error with hd path
=> solution: upgrade to emerald-cli v0.19.0

src/components/accounts/add/ImportMnemonic/importMnemonic.js, src/components/accounts/add/ImportPrivateKey/importPrivateKey.scss, src/containers/ImportMnemonic/ImportMnemonic.js, src/containers/ImportMnemonic/index.js, src/containers/Screen/screen.js
Solution: ImportMnemonicContainer component implemented
Fixes #427
=> Problem: mnemonic import does not work

src/components/common/DashboardButton/dashboardButton.test.js, src/components/tx/TxHistory/List/TxView.js, src/components/tx/TxHistory/List/list.scss, src/components/tx/TxHistory/List/transaction.js, stories/TxHistory/index.js
Solution: Transaction component refactored into TxView and Transaction container
=> Problem: Storybook does not work for Transaction component

src/components/tx/TxDetails/show.js, src/components/tx/TxHistory/List/TxView.js, src/store/wallet/history/historyActions.js, src/store/wallet/history/historyReducers.js, src/store/wallet/history/historyReducers.test.js, src/store/wallet/history/historyStorage.js, src/store/wallet/history/historyStorage.test.js, src/store/wallet/history/selectors.js, src/store/wallet/history/selectors.test.js, src/store/wallet/history/types.js
=> Fix tx history to store tx.value and tx.gasPrice as BigNumber values

src/components/tx/CreateTx/createTxForm.js, src/elements/Form/TextField/textField.js
solution: add input with identity icon
=> problem: identity icon on tx 'to' address field

electron/menus/darwin.js, electron/menus/win-linux.js, package.json
=> solution: add 'open logs' to electron menu

src/elements/LinkButton/index.js
=> problem: new linting error occured after packages update

.storybook/webpack.config.js, package.json, src/components/landing/landing.js, src/components/layout/Header/header.js, src/components/layout/Header/header.scss, src/components/layout/Header/index.js, src/components/layout/Header/status/networkSelector.js, src/components/layout/Header/status/status.js, src/components/layout/Header/total.js, src/components/layout/Main/main.js, src/components/settings/settings.js, src/containers/Screen/screen.js, src/store/ledger/ledgerActions.js, src/store/ledger/ledgerReducers.js, src/store/store.js, src/store/vault/tokens/tokenActions.js, src/store/vault/tokens/tokenReducers.js, stories/AccountEdit/index.js, stories/DashboardButton/index.js, stories/Header/index.js, stories/index.js
this refactors the header to be a material ui `<AppBar />` and use mui theme styles.
also fixed up the landing page to show the header so you can change networks on the landing screen.
fixes #437 
notes: 
- should we remove the emerald logo from the header?
- should we change the font-weight to something lighter? in the mock the letters are thin, but this is our default right now
- should i bring back currency value?
=> solution: new header

package.json
=> problem: assisted mode for NSIS installer needed

README.adoc, src/store/launcher/launcherActions.js, src/store/store.js
solution: update sync info more frequently
=> problem: during synchronization header does not show progress

src/components/accounts/AccountList/account.js, src/components/tx/CreateTx/create.js, src/components/tx/CreateTx/create.test.js
solution: disable button and check balance on select
fixes #499
=> problem: error getting balance if send clicked

src/components/accounts/GenerateAccount/PasswordDialog/passwordDialog.js, src/components/accounts/add/ImportMnemonic/importMnemonic.js, src/components/accounts/add/ImportPrivateKey/importPrivateKey.js, src/lib/validators.test.js
solution: add confirm password
fixes #483 
related to #516
=> problem: no confirm password for import and generate

package.json, src/components/accounts/AccountList/account.js, src/components/accounts/AccountShow/show.js, src/components/tx/CreateTx/createTxForm.js, src/components/tx/TxDetails/show.js
- also remove `expanded` everywhere
fixes #533
=> solution: use identity prop for account from emerald-js-ui

package.json, src/components/tx/CreateTx/multiCreateTx.js, src/components/welcome/welcome.js, src/containers/About/About.js
=> problem: old emerald logo used + welcome screen styles

src/lib/networks.js
=> problem: epool api endpoint has changed

dependencies.sh
=> Bump to emerald-cli 0.22.0

package.json
solution: fix typo in emerald-js + update emerald-js version
=> problem: block progress not working

package.json, src/components/layout/NotificationBar/NotificationBar.js
solution: move notification to top right + add styles
=> problem: notification should adhere to styleguide

src/elements/Form/TextField/textField.js
Solution: fix textfield's error style
=> Problem: misaligned error messages

src/components/accounts/SecondaryMenu/SecondaryMenu.js
=> Problem: Overlapping Menu #611

package.json, src/components/tx/SendTx/CreateTx/createTxForm.js, src/components/tx/SendTx/SignTx/SignTxForm.js, src/components/tx/SendTx/multiCreateTx.js
Solution: reset initial values via redux-form
=> Problem: create tx form keeps initial values

package.json, src/__mocks__/i18n.js, src/components/accounts/AccountShow/show.test.js, src/components/tx/TxHistory/List/TxView.js, src/components/tx/TxHistory/List/TxView.test.js
solution: add timestamp
fixes #576
=> problem: no timestamp on tx view on dashboard

src/components/tx/TxDetails/show.js
=> fix repeat display conditions

src/store/store.js, src/store/vault/accounts/accountActions.js, src/store/wallet/history/actions.js
Solution: Only call getAddressTransactions when new accounts are added and on boot
fixes #646
=> Problem: performance problems with lots of addresses

src/components/tx/TxHistory/history.js
=> Problem: tx history doesnt order by timestamp

package.json, src/components/tx/SendTx/SignTx/SignTxForm.js, src/containers/MultiCreateTransaction/MultiCreateTransaction.js
+ upgrade js-ui + change package to 1.0.0
=> Problem: sign tx form doesnt have right values

src/components/accounts/add/ImportJson/importJson.js
=> Solution: use Page component on import json

.gitignore, package-lock.json
Solution: unignore package lock file
=> Problem: No package-lock file, no vulnerability scans from github

package-lock.json, package.json, src/containers/MultiCreateTransaction/MultiCreateTransaction.js
merge https://github.com/ETCDEVTeam/emerald-js-ui/pull/64 first, and bump version in package.json
fixes #750 
While this fixes the most obvious issue, there is still something wrong with the gasPrice figure, or a bug in the current version of geth that is causing some tx's to be rejected. Still, though, this is an overall improvement.
=> fix sending max balance

package-lock.json, src/store/vault/accounts/accountActions.js, src/store/wallet/history/actions.js
=> fix tx sending

src/components/tx/SendTx/SignTx/SignTxForm.js
=> fix: deploy sign tx form styling

src/components/common/ErrorDialog/errorDialog.js, src/store/ledger/ledgerActions.js, src/store/network/networkActions.js, src/store/store.js, src/store/vault/accounts/accountActions.js, src/store/vault/tokens/tokenActions.js, src/store/wallet/history/actions.js, src/store/wallet/screen/screenActions.js
solution: display it as a temp notification
rel: fix #835
=> problem: too annoying "Fetch Error" for a remote RPC

package.json, webpack.config.js
solution: always use standard electron
=> problem: security issue with webpack-dev

packages/desktop/electron/ipc/settings.js, packages/desktop/electron/services.js, packages/desktop/src/store/launcher/launcherReducers.js, packages/desktop/src/store/wallet/selectors.js
solution: retrieve current chain from launcher state
=> problem: Wrong blockchain detecting after launch

packages/desktop/src/containers/MultiCreateTransaction/MultiCreateTransaction.js, packages/desktop/src/containers/MultiCreateTransaction/util.js, packages/desktop/src/containers/MultiCreateTransaction/util.test.js, packages/desktop/src/store/wallet/selectors.js, packages/ui/src/components/tx/send/SignTx/SignTx.tsx
solution: use Wei for calculations
rel: #828
=> problem: Insufficient funds for gas * price + value

packages/desktop/src/store/wallet/history/actions.js
solution: fix error when tracked txs check
=> problem: wrong tx status

.circleci/config.yml, .travis.yml, appveyor.yml, packages/desktop/electron/ipc/status.js, packages/desktop/gitversion.json, packages/desktop/src/containers/About/About.js, packages/desktop/src/utils/get-wallet-version.test.js, packages/ui/src/components/About/About.tsx
=> solution: About dialog show version from commit

packages/desktop/electron/services2.js, packages/desktop/src/store/vault/accounts/accountActions.js, packages/desktop/src/store/wallet/history/actions.js, packages/desktop/src/store/wallet/history/actions.test.js, packages/services/src/AddressListener.ts, packages/services/src/ApiAccess.ts, packages/services/src/ChainListener.ts, packages/services/src/TxListener.ts, packages/services/src/extractChain.spec.ts, packages/services/src/extractChain.ts, packages/services/src/services/BalanceListener.ts, packages/services/src/services/BlockchainStatus.ts, packages/services/src/services/TransactionListener.ts
solution: specify chain per request
=> problem: creates connection for each chain for every address/tx

packages/desktop/package.json, packages/desktop/src/containers/MultiCreateTransaction/MultiCreateTransaction.js, packages/desktop/src/containers/MultiCreateTransaction/util.js, packages/desktop/src/containers/MultiCreateTransaction/util.test.js, packages/desktop/src/store/network/networkActions.js, packages/desktop/src/store/vault/accounts/accountActions.js, packages/ui/package.json, packages/ui/src/components/tx/send/CreateTx/CreateTx.spec.tsx, packages/ui/src/components/tx/send/CreateTx/CreateTx.tsx, packages/ui/src/components/tx/send/CreateTx/ToField/ToField.tsx, packages/ui/src/components/tx/send/SignTx/SignTx.tsx, packages/workflow/.gitignore, packages/workflow/package.json, packages/workflow/src/create-tx/CreateErc20Tx.spec.ts, packages/workflow/src/create-tx/CreateErc20Tx.ts, packages/workflow/src/create-tx/CreateEthereumTx.spec.ts, packages/workflow/src/create-tx/CreateEthereumTx.ts, packages/workflow/src/create-tx/types.ts, packages/workflow/src/display/DisplayEtherTx.spec.ts, packages/workflow/src/display/DisplayEtherTx.ts, packages/workflow/src/display/DisplayTx.ts, packages/workflow/src/index.ts, packages/workflow/tsconfig.json
solution: refactor and move out tx creation workflow
=> problem: sending MAX transaction produces incorrect values

packages/desktop/electron/ipc/status.js, packages/desktop/src/containers/About/About.js, packages/ui/src/components/About/About.tsx
solution: remove, it doesn't make sense with embedded Vault
=> problem: displays Vault version as UNKNOWN

packages/desktop/electron/main.js, packages/electron-app/src/application/Application.ts, packages/electron-app/src/createServices.ts, packages/services/src/emerald-client/ApiAccess.ts, packages/services/src/index.ts, packages/services/src/services/BlockchainStatusService.ts, packages/services/src/services/ConnStatus.ts, packages/services/src/services/Services.ts, packages/services/src/services/balances/BalanceListener.ts, packages/services/src/services/prices/PricesService.ts, packages/services/src/services/transactions/TxListener.ts, packages/services/src/services/transactions/TxService.ts
solution: try to reconnect if window state changed
=> problem: may lose a connection if not used for a long time

packages/core/package.json, packages/ledger/package.json, packages/react-app/package.json, packages/store/package.json, packages/vault/package.json, yarn.lock
solution: upgrade to vault with fix
=> problem: doesn't run on macOS High Sierra

.github/workflows/build.yaml, .github/workflows/test.yaml, js-green-licenses.json, packages/react-app/package.json, packages/react-app/src/create-wallet/CreateWalletWizard.tsx, packages/react-app/src/create-wallet/SelectKeySource.tsx, packages/ui/src/components/accounts/ImportMnemonic/ImportMnemonic.tsx, packages/ui/src/components/common/PasswordInput/ConfirmedPasswordInput.tsx, packages/ui/src/components/common/PasswordInput/PasswordInput.tsx, packages/ui/stories/ImportMnemonic/index.tsx, yarn.lock
This PR allows users import 12 word mnemonic phrases from popular wallets.
It also validate mnemonic phrases to prevent funds losing by users.
=> bip39 mnemonic validation added

packages/react-app/src/common/EthTxSettings/EthTxSettings.tsx, packages/react-app/src/transaction/CreateApproveTransaction/SetupApproveTransaction.tsx, packages/react-app/src/transaction/CreateTransaction/CreateTransaction.tsx, packages/react-app/src/transaction/CreateTx/CreateTx.tsx
solution: always use BigAmount instead of a float which gets corrupted
=> problem: uses zero fee for transaction

.yarnrc.yml, package.json, packages/core/package.json, packages/electron-app/package.json, packages/persistent-state/package.json, packages/react-app/package.json, packages/services/package.json, packages/store/package.json, packages/store/src/transaction/actions.ts, yarn.lock
solution: upgrade to the latest Vault where it's fixed
=> problem: produces and invalid signature with Ledger

.yarnrc.yml, packages/electron-app/src/windows/MainWindow.ts, packages/react-app/src/app/AboutDialog/About/About.tsx, packages/services/src/jsonrpc/JsonRpc.ts, packages/services/src/services/balance/BalanceService.ts, yarn.lock
problem: ethers provider not working
problem: can't click a help link
=> solution: fixes for several problems
