README.adoc, electron/package.js, package.json, src/store/tokenActions.js
- `npm run package:all` command builds electron packages for linux and win32 platforms
- README has been updated
=> Packaging Electron for Windows and Linux (npm run package:all)

.eslintrc, README.adoc, package.json, src/components/accounts/list.js, src/components/accounts/show.js, src/components/tx/list.js, src/lib/types.js, src/store/networkActions.js, src/store/store.js
- Updates `.eslintrc` to accommodate some warnings I was getting
- Updates a couple of files  -- only as I came across them (far from complete) -- to use those eslinter settings
+ `single-quotes`,
+ `object-shorthand`,
+ `object-curly-spacing`...
I'm not set on these settings; if you have other preferences I'm happy to adjust to whatever works. I would just like to make the code (eventually) compatible with the linter in any case.
- Updates `store/networkActions.js` to use a much slower polling interval for sync status. 1/second was drowning my computer. This patch is not ideal -- it should eventually _not_ be hardcoded, instead it should be configured as a node flag or something else -- but I haven't figured out how to do that yet. I'm not set on this; will be happy to revert if I'm the …
=> eslint syntax, fix `getFiat`, and isaac's happier settings for development

src/components/accounts/account.js, src/components/accounts/list.js, src/components/accounts/popup.js, src/components/accounts/show.js, src/components/layout/total.js, src/components/tx/create.js, src/components/tx/createTxForm.js, src/components/tx/list.js, src/components/tx/show.js, src/components/tx/transaction.js, src/lib/convert.js, src/lib/rpcApi.js, src/lib/styles.js, src/lib/types.js, src/store/accountActions.js, src/store/accountReducers.js, src/store/tokenActions.js
- Implements tx history display for account pages
- Implements persistent tx history via `localStorage`, which wasn't slated for Beta but was slowing down my development process. If would rather leave out of this release I'm happy keeping the changes just on my machine in my `git stash` of goodies.
- Fixes transactions not updating from 'PENDING'
- Fixes extra "$" in `total.js`, which was due to me developing on Safari (fixed with Chrome) - Safari didn't like `toLocaleString()`
- Fixes create Tx form balance field from looking weird
- Changes formatting on create Tx form to give more space to `To` address field.
- Fixes rpc erroring on receiving `result: false` from `eth_sync` call
- Fixes a couple of `PropType.array.isRequired` cases that should have been `.object.` because they're …
=> Tx histories

electron/main.js, electron/mainWindow.js, package.json, src/components/layout/footer.js, src/components/layout/navigation.js, src/components/layout/status.js, src/components/layout/total.js, src/components/main.js, src/components/screen.js, src/components/welcome.js, src/store/launcherReducers.js, src/store/store.js
rel #159 
refine welcome screen, with regard to footer and beta disclaimer
- uses localStorage to track 'firstRun' so welcome screen only shows once,
with a button to continue to the wallet; ideally we'd store this in the appdata fs along with other user settings but this'll do for starters
=> welcome screen & footer revisions

src/components/layout/footer.js, src/components/tx/list.js
rel #168 
While an incremental improvement for the time being, it opens the idea of handling the bigger picture when 0accts and/or 0txs exist... the space might eventually be better spent with some big ol' buttons and informative content about accounts /+ transactions
=> display empty txs better and send links to browser

package.json, src/components/accounts/SecondaryMenu/index.js, src/store/vault/accounts/accountActions.js, src/store/vault/tokens/tokenActions.js, src/store/wallet/settings/settingsActions.js, src/store/wallet/settings/settingsReducers.js
depends on: https://github.com/ethereumproject/emerald-js/pull/20
=> fix(unhide accounts):

.travis.yml, appveyor.yml, package.json
- AppVeyor: publish build not only from master branch but from tags too
- Travis CI: don't compile emerald-cli from sources - downlod it from github.com releases page
=> Continues Delivery fixes

package.json
It unexpectedly rejected downloading geth process if geth exists.
It has already been fixed so the PR uses that fixed version of emerald-js.
https://github.com/ethereumproject/emerald-js/pull/31
=> Fix initialization error

dependencies.sh
Ideally, rust/cargo wouldn't be a dependency for emerald-wallet. Perhaps using something like [ffi](https://github.com/node-ffi/node-ffi) would be ideal here, but at the very least this PR solves
1. Write new path to `~/.profile` so that cargo remains properly installed across terminal sessions
2. Only install emerald-cli if the version installed to `$PATH` is mismatched with `EMERALD_CLI_VER`
3. Early exit if all conditions are met
4. unset `RUSTFLAGS` after installing (cleanup)
5. using named functions should make it easier to debug / understand whats going on.
worth noting that currently this doesn't work, as 0.17.0 relies on an unpublished version of emerald-rocksdb. However, [another PR](https://github.com/ethereumproject/emerald-wallet/pull/447) bumps the version to 0.19.0 which …
=> write cargo path update to .profile and only install if needed

electron/ipc/index.js, electron/ipc/privateKey.js, src/components/accounts/add/ImportPrivateKey/importPrivateKey.js
solution: loading indicator on button and take importing off render thread with ipc
fixes #440
=> problem: no visual indicator for importing private key

src/components/tx/CreateTx/create.js
Empty string for data prop for eth_estimateGas rpc call will return error in case of Parity
solution: Do not provide empty string for data prop for eth_estimateGas call
fixes https://github.com/ethereumproject/emerald-wallet/issues/472
=> problem: Empty string for data prop for eth_estimateGas rpc call 

dependencies.sh
The cargo install script sets the path for us, so we don't need this anymore.
Testing notes:
1. Completely uninstall rust/cargo
2. remove ~/.cargo/bin/emerald if it exists still
3. run the `dependencies.sh` script
4. Assert that emerald is avail on your path
5. open a new shell and do 4 again
=> No longer need to set path

src/components/layout/Header/index.js
solution: only show sync progress when actually 'syncing'
note:
theres an underlying issue here where the `network.sync.highestBlock` and `network.currentBlock.height` will be out of sync because they are on different timers.
fixes #517
=> problem: header shows negative values

electron/launcher.js
solution: set cache to 1024mb for a performance increase in syncing
fixes #512 
I've tested this, I was able to do a full sync in 3 hours from emerald-wallet as opposed to 1-2days with it set as the default.
=> problem: syncing takes a long time

src/components/welcome/NodeTypeChoice/nodeTypeChoice.js, src/lib/networks.js, src/lib/rpc/gethProviders.js
solution: move epool down the network select menu in favor of gastracker.io
=> problem: epool is experiencing heavy traffic

src/components/layout/Main/main.js, src/components/welcome/welcome.js
solution: show header on welcome screen
fixes #344 
fixes #380 
fixes #522 
fixes #481 
fixes #521 
fixes #495 
fixes #492 
fixes #446 
fixes #525 
this solves some startup loop problems for people trying to use `epool` and it being down or giving `502`'s. they should be able to switch back to mainnet or gastracker
=> problem: can't switch network on welcome screen

src/components/accounts/AccountEdit/accountEdit.js, src/components/accounts/AccountEdit/accountEdit.test.js
solution: use textColor for inputs + remove description and address from edit form
fixes #610
=> Problem: edit account hard to see

src/components/common/ErrorDialog/errorDialog.js, src/store/launcher/launcherActions.js, src/store/middleware/index.js, src/store/middleware/promise-catch-all.js, src/store/network/index.js, src/store/network/networkActions.js, src/store/store.js, src/store/wallet/screen/screenActions.js, src/store/wallet/screen/screenReducers.js
=> add error dialogs for uncaught network errors

src/components/tx/TxHistory/List/TxView.js, src/components/tx/TxHistory/List/list.js, src/components/tx/TxHistory/List/list.scss
solution: remove repeat button and re-align tx list
=> problem: repeat button useless and taking up too much room

package.json, src/components/tx/TxHistory/List/TxView.js, src/components/tx/TxHistory/List/transaction.js, src/store/vault/tokens/tokenActions.js
Solution: show token value of sent txes
fixes #644
=> Problem: tx history doesnt show token values

src/store/network/networkActions.js
Solution: suppress error and use the redux logger to log it
fixes #653 
fixes #654
=> Problem: method not exist error on morden when switching networks

package.json
The current project is not capable of multi-platform testing. Therefore, it was changed to be practicable in the Window Environment.
=> command Cross-platform support

packages/react-app/package.json, packages/react-app/src/wallets/WalletDetails/WalletDetails.tsx, packages/react-app/src/wallets/WalletList/WalletItem.tsx, packages/ui/package.json, packages/ui/src/components/accounts/WalletReference.tsx, packages/ui/src/components/common/HashIcon/HashIcon.tsx, packages/ui/src/components/common/HashIcon/index.ts, packages/ui/src/index.ts, yarn.lock
If wallet list contains many items its slowdown rendering. The reason is `hashicon().toDataURL()` call. I copied Hashicon react component and optimized it a bit.
=> problem: Hashicon should not rerender with same props values

.github/workflows/verify.yaml
Official JSGL has an issue with version names, which is patched at https://github.com/google/js-green-licenses/pull/230 but is not merged yet. Use our patched version until it's merged and released.
=> Use patched JSGL
